### ISSUE TITLE
Compatibility with GPP

### ISSUE THREAD

**Issue by eberkain** [linuxgurugamer/StateFundingContinued#1]
I was using this fine with the default kerbin system and SD to scale everything to 6.4x, but after switching over to Galileo's Planet Pack this is not working anymore.  When loading a new career start I get the initial option to pick which group I want to use, but the selection button does nothing and there is no way to get rid of the window.  Sorry I can't be more specific, not near my game install right now.

**Comment by linuxgurugamer** [comment]
Log file, please

**Comment by eberkain** [comment]
https://drive.google.com/open?id=0B_wAo_KZdHCrNm5MeHFpTHNVNlU
https://drive.google.com/open?id=0B_wAo_KZdHCrTk5TWHhraXU1Z3c

ksp log and output log.  I pulled out most of the part mods so reduce change of it being a conflict, still same problem.  I get an exception when loading a new career game, I can press the control bar button a couple times to get the menu to go away, load to the vab and and then exit, and the menu is back up and throws another exception.

**Comment by linuxgurugamer** [comment]
Fixed in release
