### ISSUE TITLE
StateFundingSettings not being written to PARAMETERS

### ISSUE THREAD

**Issue by 7ranceaddic7** [linuxgurugamer/StateFundingContinued#13]
KSPv 1.4.5
StateFundingv 0.6.16

LoaderInfo: https://drive.google.com/open?id=1CuBu6Lu0iOybzHax0Ji73dp4JiWk28xhUDO2-cKt_QA

I have a HEAVILY modded install where this is not present in the .sfs

		StateFundingSettings
		{
			enabled = True
			budgetPeriodsPerYear = 12
			stopWarpAtBudgetPeriod = True
			stopWarpOnNewYear = True
		}

As a result, exceptions like these are being thrown ...

181026T190026.458 [EXCEPTION] [GameParameters.CustomParams[StateFundingSettings]] ArgumentException: Couldn't find custom parameter StateFundingSettings!
   at GameParameters.CustomParams[StateFundingSettings] ()
   at StateFunding.OnSpaceCentre.Start ()

I'm opening this issue as a record of my debug process which will require rebuilding with Stock+StateFunding as a base install.  Any advice is welcome.

**Comment by 7ranceaddic7** [comment]
I have traced this to an unanticipated effect of SettingsMaster behavior.

I am closing this to open an issue in SettingsMaster.

**Comment by linuxgurugamer** [comment]
Please remove the SettingsMaster, it doesn't work and causes problems as you just found out
