### ISSUE TITLE
Mod not Functioning

### ISSUE THREAD

**Issue by PawelW2006** [linuxgurugamer/StateFundingContinued#20]
== Issue ==
After extracting the "StateFunding" Folder into Gamedata no features of the mod appear in game. When creating a new save there is no State Funding tab in the DIfficulty Settings and Upon creation of a new save there is no prompt to choose the state.
- Contents of the StateFunding folder copied into GameData are as following:
- Assets Folder
- Data Folder
- PluginData Folder
- Plugins Folder
- License.txt
- MM_StateFunding.cfg
- README.md
- StateFunding.version

== Additional Information ==
- I have tried installing it via CKAN, manually from Spacedock and manually from GIthub, it always failed.
- All the required dependencies are installed and no errors are shown during or after the game loading.

== Mods Installed Beside StateFunding ==
- Kopernicus + OPM
- Neartea Mods
None of those mods interfere with the contracts or money system and they did work with StateFunding when i played it back on 1.5 or 1.6 i think.

== Technical Details ==
OS: Linux Mint 21 x86_64
CPU/APU: Ryzen 7 5800H
GPU: RTX 3070 "MaxQ" with NVIDIA Proprietary driver 515.65.01
RAM: 32gb DDR4, KSP Uses only around 5gb.
Storage: 1tb NVME SSD formatted in EXT4 with small Swap Partition
Desktop Enivornment: Cinnamon 5.4.8
KSP Version: 1.12.3 Linux Native
Mod Version: Latest at the time of writing

Note: The Software and/or Hardware has no problems/conflicts with any other Games or Mods to any Games including KSP

**Comment by linuxgurugamer** [comment]
You are asking for support, not reporting a bug (yet)

Please ask for help on the Forum, and while you provided a lot of good info, you didn't include the log file

I don't do support work here

The only thing you didn't mention was what kind of game you were playing.  Please post all this info along with the log file (Player.log) and the game info on the forum:  http://forum.kerbalspaceprogram.com/index.php?/topic/156984-12-state-funding-continued/
