### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by Jimbodiah** [linuxgurugamer/StateFundingContinued#5]
Hi,

I've been using this mod on a new career I started, but have trouble seeing what this mod does except add a page to the menu bar.

I am in my first quarter, received 12000 in state funding, but I made about 20M funds just by doing normal contract missions, 9M left over after maxing out KSC and doing all my launches. What is the idea behind this mod, maybe I am just missing the intended goal?

**Comment by linuxgurugamer** [comment]
This isn't an issue, please ask the question in the thread.
