### ISSUE TITLE
Compatibility Issues with Kerbalism (Potential Fix included)

### ISSUE THREAD

**Issue by RagingGamer** [linuxgurugamer/StateFundingContinued#9]
My satellites weren't being counted for coverage. Perhaps due to changes Kerbalism makes.
It may also have been the cause of RemoteTech, but I don't know whether or not it changes the antennas.

In any case, PhilM on the forums helped me figure this out. (and by that I mean did all the legwork)
Just posting here JIC.

` 

>        Item
>         {
>                 name = Communication
>                 Modules
>                 {
>                         Item
>                         {
>                                 name = ModuleDataTransmitter
>                         }
>                         Item
>                         {
>                                 name = ModuleLimitedDataTransmitter
>                         }
>                         Item
>                         {
>                                 name = ModuleRTAntenna
>                         }
>                         Item
>                         {
>                                 name = AntennaRange
>                         } //below is the added code for a potential fix
>                         Item 
>                         {
>                                 name = Antenna
>                         }
>                 }
>         }

`

**Comment by linuxgurugamer** [comment]
Added in new release
